version: "3"

services:
  app:
    container_name: music-app
    restart: always
    build: .
    ports:
      - "9000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "9001:27017"
    logging:
      driver: none